### ISSUE TITLE
LSPDFR crashes when pressing enter on an empty "PENDING RESULTS" item

### ISSUE THREAD

**Issue by yoep** [Albo1125/British-Policing-Script#3]
**Version:** 1.1.0.0
**Conditions:** No pending results items are available (empty list)
**Reproducable:** yes

**Reproduction steps:**
* Open the menu with F9
* Select "Magistrates' Court Results" in the menu
* Press enter on the empty pending result item (see screenshot)
* Rage shows the error message that LSPDFR has crashed

**Stacktrace:**

> [5/19/2019 12:12:15 PM.614] LSPD First Response: ==============================
[5/19/2019 12:12:15 PM.614] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[5/19/2019 12:12:15 PM.615] LSPD First Response: ------------------------------
[5/19/2019 12:12:15 PM.615] LSPD First Response: Origin: Rage.SleeplessGameFiber
[5/19/2019 12:12:15 PM.615] LSPD First Response: ------------------------------
[5/19/2019 12:12:15 PM.616] LSPD First Response: Exception type: System.NullReferenceException
[5/19/2019 12:12:15 PM.616] LSPD First Response: Exception message: Object reference not set to an instance of an object.
[5/19/2019 12:12:15 PM.616] LSPD First Response: ------------------------------
[5/19/2019 12:12:15 PM.617] LSPD First Response: Inner exceptions:
[5/19/2019 12:12:15 PM.617] LSPD First Response: ------------------------------
[5/19/2019 12:12:15 PM.617] LSPD First Response: Stack trace:
[5/19/2019 12:12:15 PM.618] LSPD First Response: at RAGENativeUI.PauseMenu.TabSubmenuItem.ProcessControls()
[5/19/2019 12:12:15 PM.618] at RAGENativeUI.PauseMenu.TabView.ProcessControls()
[5/19/2019 12:12:15 PM.618] at RAGENativeUI.PauseMenu.TabView.Update()
[5/19/2019 12:12:15 PM.618] at British_Policing_Script.Menus.Process(Object sender, GraphicsEventArgs e)
[5/19/2019 12:12:15 PM.619] at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
[5/19/2019 12:12:15 PM.619] at Rage.Game.RaiseFrameRender(GraphicsEventArgs e)
[5/19/2019 12:12:15 PM.619] at Rage.RemotePlugin.HandleRenderFiber()
[5/19/2019 12:12:15 PM.620] at Rage.GameFiber.Main()
[5/19/2019 12:12:15 PM.620] LSPD First Response: ==============================

**Screenshot:**
![screenshot](https://i.imgur.com/GnEaNAg.png)

**Comment by Albo1125** [comment]
Thanks for fixing @yoep
